# Netlifyの基本的なビルド設定
[build]
  # 公開するフォルダを指定します。今回はプロジェクトのルートにあるindex.htmlを公開します。
  publish = "."
  # サーバーレス関数が置かれているフォルダを指定します。
  functions = "functions"

# ビルド時に使用する環境変数を設定します
[build.environment]
  # これで、ビルド全体で使用するPythonのバージョンを3.11に指定します。
  # この方がより確実に認識されることがあります。
  PYTHON_VERSION = "3.11"

# --- ここからが最終手段の追記です ---
# 関数を一つ一つ明示的に指定します
[[functions]]
  # これで "koyomi" という名前の関数を強制的に認識させます
  name = "koyomi"
  # この設定は必須ではありませんが、念のため記述します
  runtime = "python3.11"
