# Netlifyの基本的なビルド設定
[build]
  # 公開するフォルダを指定します。今回はプロジェクトのルートにあるindex.htmlを公開します。
  publish = "."
  # サーバーレス関数が置かれているフォルダを指定します。
  functions = "netlify/functions"

# ビルド時に使用する環境変数を設定します
[build.environment]
  # これで、ビルド全体で使用するPythonのバージョンを3.11に指定します。
  # この方がより確実に認識されることがあります。
  PYTHON_VERSION = "3.11"

